---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg"
    prometheus.io/port: "9180"
    prometheus.io/scrape: "true"
  labels:
    provider: "fabric8"
    app: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "content-repository"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "content-repository"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
